export const keyboardSingleCodes = [
  {
    code: "49",
    key: "1",
    type: "number",
  },
  { code: "50", key: "2", type: "number" },
  { code: "51", key: "3", type: "number" },
  { code: "52", key: "4", type: "number" },
  { code: "53", key: "5", type: "number" },
  { code: "54", key: "6", type: "number" },
  { code: "55", key: "7", type: "number" },
  { code: "56", key: "8", type: "number" },
  { code: "57", key: "9", type: "number" },
  { code: "48", key: "0", type: "number" },
  { code: "190", key: ".", type: "number_separator" },
  { code: "189", key: "-", type: "operation" },
  { code: "187", key: "=", type: "operation" },
  { code: "13", key: "=", type: "operation" },
  { code: "191", key: "/", type: "operation" },
  { code: "8", key: "delete", type: "clear" },
  { code: "27", key: "c", type: "clear" },
  { code: "46", key: "ce", type: "clear" },
];
export const keyboardMultipleCodes = [
  { firstCode: "18", secondCode: "189", key: "sign", type: "number_sign" },
  { firstCode: "16", secondCode: "187", key: "+", type: "operation" },
  { firstCode: "16", secondCode: "56", key: "x", type: "operation" },
  { firstCode: "17", secondCode: "221", key: "square", type: "operation" },
  { firstCode: "17", secondCode: "219", key: "root", type: "operation" },
  { firstCode: "16", secondCode: "53", key: "%", type: "operation" },
  { firstCode: "17", secondCode: "76", key: "MC", type: "mrc" },
  { firstCode: "18", secondCode: "82", key: "MR", type: "mrc" },
  { firstCode: "18", secondCode: "80", key: "M+", type: "mrc" },
  { firstCode: "17", secondCode: "81", key: "M-", type: "mrc" },
  { firstCode: "17", secondCode: "77", key: "MS", type: "mrc" },
];
